# see http://fireeagle.yahoo.net/developer/manage for your keys
fireeagle:
  consumer_key: CONSUMER_KEY
  consumer_secret: CONSUMER_SECRET
  general_purpose_access_token: GP_AT
  general_purpose_token_secret: GP_TS
  # https://fireeagle.yahoo.net/oauth/mobile_auth/XXX
  mobile_app_id: 1234